name: CI

on:
  push:
  pull_request:

jobs:
  PHPUnit:
    name: PHPUnit (PHP ${{ matrix.php }})
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php:
          - 8.3
          - 8.2
          - 8.1
          - 8.0
          - 7.4
          - 7.3
          - 7.2
          - 7.1
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          ini-file: development
      - run: composer install
      - run: vendor/bin/phpunit --coverage-text
        if: ${{ matrix.php >= 7.3 }}
      - run: vendor/bin/phpunit --coverage-text -c phpunit.xml.legacy
        if: ${{ matrix.php < 7.3 }}
      - run: time php examples/91-benchmark-throughput.php

  PHPUnit-macOS:
    name: PHPUnit (macOS)
    runs-on: macos-12
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: xdebug
          ini-file: development
      - run: composer install
      - run: vendor/bin/phpunit --coverage-text
      - run: time php examples/91-benchmark-throughput.php

  PHPUnit-hhvm:
    name: PHPUnit (HHVM)
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: cp "$(which composer)" composer.phar && ./composer.phar self-update --2.2 # downgrade Composer for HHVM
      - name: Run hhvm composer.phar install
        uses: docker://hhvm/hhvm:3.30-lts-latest
        with:
          args: hhvm composer.phar install
      - name: Run hhvm vendor/bin/phpunit
        uses: docker://hhvm/hhvm:3.30-lts-latest
        with:
          args: hhvm vendor/bin/phpunit
      - name: Run time hhvm examples/91-benchmark-throughput.php
        uses: docker://hhvm/hhvm:3.30-lts-latest
        with:
          args: bash -c "time hhvm examples/91-benchmark-throughput.php"
